---
- hosts: localhost
  become: yes
  gather_facts: no
  vars:
      git_repo_url: https://github.com/karthikgavipuram/node_helloworld.git
      repo_path: /path/node_helloworld
      repo_branch: main
  tasks: 
  - name: Run the equivalent of "apt-get update" as a separate step
    apt:
     update_cache: yes
  - name: Ansible shell module multiple commands
    shell: 'curl -fsSL https://deb.nodesource.com/setup_14.x | sudo -E bash -'
  - name: Install reqired packages
    apt: name={{ item }} state=present
    with_items:
      - git
      - curl
      - wget
      - nginx
      - nodejs
   - name: Install packages based on package.json using the npm
    npm:
      path: "{{ repo_path }}"
      state: present
  - name: Build app
    command: npm run build
    args:
      chdir: "{{ repo_path }}"
   - name: Copy folder to /var/www
    copy:
     src: "{{ repo_path }}/build"
     dest: /var/www
